version: "3.9"

services:
  backend:
    image: zikaelson/fastapi-diabetes-backend:latest
    ports:
      - "8000:8000"

  frontend:
    image: zikaelson/diabetes-streamlit-frontend:latest
    ports:
      - "8501:8501"
    depends_on:
      - backend
